package Gui;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.util.StringTokenizer;
import javax.swing.*;

public class selector extends JPanel {
    private JButton jb1;
    private JButton jb2;
    private JButton jb3;
    private JButton jb4;
    private JTextArea jcomp5;
    private JTextArea jcomp6;
    private JTextArea jcomp7;
    private JTextArea jcomp8;
    File fl;


    public selector() {
        //construct components
        jb1 = new JButton ("Load");
        jb2 = new JButton ("Reverse");
        jb3 = new JButton ("Rev 2w.");
        jb4 = new JButton ("Count");
        jcomp5 = new JTextArea (5,5);
        jcomp6 = new JTextArea (5,5);
        jcomp7 = new JTextArea (5,5);
        jcomp8 = new JTextArea (5,5);


        //adjust size and set layout
        setPreferredSize(new Dimension(722, 842));
        setLayout (null);

        //add components
        add (jb1);
        add (jb2);
        add (jb3);
        add (jb4);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);

        //set component bounds (only needed by Absolute Positioning)
        jb1.setBounds (5, 30, 100, 20);
        jb2.setBounds (135, 30, 100, 20);
        jb3.setBounds (265, 30, 95, 20);
        jb4.setBounds (385, 30, 100, 20);
        jcomp5.setBounds (5, 50, 100, 285);
        jcomp6.setBounds (135, 50, 100, 285);
        jcomp7.setBounds (265, 50, 95, 285);
        jcomp8.setBounds (385, 50, 100, 285);

        //Button one to open file
        jb1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            JFileChooser jfc = new JFileChooser();
                jfc.showOpenDialog(jfc);
                fl = jfc.getSelectedFile();
                try {
                    BufferedReader br = new BufferedReader(new FileReader(fl));
                    String str1 = "one";
                    str1 = br.readLine();
                    while(str1.length() > 0){
                    jcomp5.append(str1);
                        jcomp5.append("\n");
                        str1 = br.readLine();
                    }
                }catch(Exception ee)
                {
                    ee.printStackTrace();
                    System.out.println("It did not work");
                }
            }
        });



        //Button one to swap each word
        jb2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                String[] tokens;
                int i = 0;

                try {
                    BufferedReader br = new BufferedReader(new FileReader(fl));
                    System.out.println("Im here 1");
                    String str1 = "one";
                    str1 = br.readLine();
                    while(str1.length() > 0){
                        tokens = str1.split(" ");
                        System.out.println("Im here 2");
                        i = tokens.length;
                        System.out.println("Im here 3");
                        System.out.println(i);
                        for(int x = i; x > 0; x--) {
                            jcomp6.append(tokens[x-1]+" ");
                        }
                        jcomp6.append("\n");
                        str1 = br.readLine();


                    }
                }catch(Exception ee)
                {
                    ee.printStackTrace();
                    System.out.println("It did not work");
                }



            }
        });




        //Button one swat 2 words
        jb3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        //Button one to count letters
        jb4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });

    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("GuiGene");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new selector());
        frame.setVisible (true);
    }
}
